---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: firewall_db
    image: rockylinux:8
    image_version: latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    pre_build_image: false
    privileged: true
    groups:
      - db
      - docker
  - name: firewall_web
    image: rockylinux:8
    image_version: latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    pre_build_image: false
    privileged: true
    groups:
      - docker
      - web
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  log: true
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
  inventory:
    links:
      group_vars: ../resources/inventory/group_vars/
verifier:
  name: ansible
