---
- name: Converge
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Wait for systemd to complete initialization. # noqa command-instead-of-module
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 0

  tasks:
    - name: Include ansible-role-firewalld
      ansible.builtin.include_role:
        name: mirsg.firewalld
