---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: firewall_db
    image: ${MOLECULE_DOCKER_IMAGE:-centos:7}
    image_version: latest
    command: ""
    pre_build_image: false
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    groups:
      - db
      - docker

  - name: firewall_web
    image: ${MOLECULE_DOCKER_IMAGE:-centos:7}
    image_version: latest
    command: ""
    pre_build_image: false
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    groups:
      - docker
      - web

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  log: true
  inventory:
    links:
      group_vars: ../resources/inventory/group_vars/
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml

lint: |
  set -e
  yamllint .
  ansible-lint

verifier:
  name: ansible
