---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: firewall_db
    image: centos/systemd
    image_version: latest
    command: ""
    pre_build_image: false
    privileged: true
    groups:
      - db
      - docker
    tmpfs:
      - /run
      - /tmp

  - name: firewall_web
    image: centos/systemd
    image_version: latest
    command: ""
    pre_build_image: false
    privileged: true
    groups:
      - docker
      - web
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  log: true
  playbooks:
    converge: ../resources/converge.yml
    verify: ../resources/verify.yml
  inventory:
    links:
      group_vars: ../resources/inventory/group_vars/
verifier:
  name: ansible
