{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN if [ $(command -v dnf) ]; then dnf -y install bash sudo iproute firewalld firewall-config firewall-applet; dnf clean all; \
    elif [ $(command -v yum) ]; then yum install -y sudo yum-plugin-ovl bash iproute firewalld firewall-config firewall-applet && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    fi

STOPSIGNAL SIGRTMIN+3
CMD [ "/sbin/init" ]
